services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/acme.json:/acme.json
      - ./docker/traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true